name: alpha-package

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  alpha-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Get Local Version
        id: local_version
        run: |
          echo "VERSION=$(cat ${{ github.workspace }}/package.json | jq '.version')" >> $GITHUB_OUTPUT
          echo "PKG_NAME=$(cat ${{ github.workspace }}/package.json | jq '.name')" >> $GITHUB_OUTPUT
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HAS_PERIOD: ${{ contains(steps.local_version.outputs.VERSION, 'alpha') || contains(steps.local_version.outputs.VERSION, 'beta') || contains(steps.local_version.outputs.VERSION, 'rc') }}
        run: |
          if [[ $(npm view ${{ format('{0}@{1}', steps.local_version.outputs.PKG_NAME, steps.local_version.outputs.VERSION) }}) ]] || [[ ${{ env.HAS_PERIOD }} == false ]]; then
            echo "the package has published."
          else
            npm install
            npm run build
            npm publish --access public
          fi
  
